export const SSEEventType = {
  SANDBOX_CREATED: "SANDBOX_CREATED",
  TASK_STARTED: "TASK_STARTED",
  TASK_COMPLETED: "TASK_COMPLETED",
  TASK_FAILED: "TASK_FAILED",
  TASK_ABORTED: "TASK_ABORTED",
  TASK_ACTION_STARTED: "TASK_ACTION_STARTED",
  TASK_ACTION_COMPLETED: "TASK_ACTION_COMPLETED",
  TASK_REASONING: "TASK_REASONING",
};

export const ERROR_TYPES = {
  NETWORK_ERROR: "NETWORK_ERROR",
  TIMEOUT_ERROR: "TIMEOUT_ERROR",
  ABORTED_ERROR: "ABORTED_ERROR",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",

  VALIDATION_ERROR: "VALIDATION_ERROR",

  SANDBOX_ERROR: "SANDBOX_ERROR",
  SANDBOX_ACTION_ERROR: "SANDBOX_ACTION_ERROR",

  AI_CLIENT_ERROR: "AI_CLIENT_ERROR",
  AI_CLIENT_TASK_ERROR: "AI_CLIENT_TASK_ERROR",

  SESSION_ERROR: "SESSION_ERROR",
};

export const MESSAGE_ROLE = {
  SYSTEM: "system",
  USER: "user",
  ASSISTANT: "assistant",
  ASSISTANT_TASK_ACTION: "assistant_task_action",
};
