export const SSEEventType = {
  SANDBOX_CREATED: "SANDBOX_CREATED",
  TASK_STARTED: "TASK_STARTED",
  TASK_COMPLETED: "TASK_COMPLETED",
  TASK_ERROR: "TASK_ERROR",
  ACTION_STARTED: "ACTION_STARTED",
  ACTION_COMPLETED: "ACTION_COMPLETED",
  REASONING: "REASONING",
};
