export const SSEEventType = {
  SANDBOX_CREATED: "SANDBOX_CREATED",
  TASK_STARTED: "TASK_STARTED",
  TASK_COMPLETED: "TASK_COMPLETED",
  TASK_ERROR: "TASK_ERROR",
  ACTION_STARTED: "ACTION_STARTED",
  ACTION_COMPLETED: "ACTION_COMPLETED",
  REASONING: "REASONING",
};

export const MAX_WIDTH = 1024;
export const MAX_HEIGHT = 768;
export const MIN_WIDTH = 640;
export const MIN_HEIGHT = 480;
